name: teknikal_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraBold.ttf 
          weight: 900
        - asset: fonts/Nunito-Bold.ttf
          weight: 800
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 700
        - asset: fonts/Nunito-Medium.ttf
          weight: 600
        - asset: fonts/Nunito-Regular.ttf
          weight: 500
        - asset: fonts/Nunito-Light.ttf
          weight: 300